# AutoBot - AI-Powered Automation Platform
# Copyright (c) 2025 mrveiss
# Author: mrveiss
---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart slm backend
  ansible.builtin.systemd:
    name: "{{ slm_backend_service }}"
    state: restarted
  ignore_errors: true

- name: test nginx config
  ansible.builtin.command:
    cmd: nginx -t

- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: restart grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
