# AutoBot - AI-Powered Automation Platform
# Copyright (c) 2025 mrveiss
# Author: mrveiss
---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart slm-agent
  ansible.builtin.systemd:
    name: slm-agent
    state: restarted
    daemon_reload: true
