---
# Common role variables

common_packages:
  - python3
  - python3-pip
  - python3-venv
  - git
  - curl
  - wget
  - vim
  - htop
  - net-tools
  - ufw
  - rsync
  - ca-certificates
  - gnupg
  - lsb-release

autobot_user: autobot
autobot_home: /home/autobot

# Emergency admin user for fallback access when SSH keys fail
emergency_admin_user: autobot_admin
emergency_admin_password_hash: "$6$rounds=656000$VqQZbIggJvVNjHfl$hunhLQdMKj/TCyE.ftDknskbz4SCnGz5e6Yo4YJzHeIIhdRAp/oIDKdwd54oktyBwmb2nP09MWRyXNu0mLg1L1"

autobot_directories:
  - "{{ autobot_home }}/autobot-vue"
  - "{{ autobot_home }}/backend"
  - "{{ autobot_home }}/logs"
  - "{{ autobot_home }}/data"
  - "{{ autobot_home }}/config"
  - "{{ autobot_home }}/scripts"
  - "/var/log/autobot"
