---
# Handlers for time synchronization role

- name: restart systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    state: restarted
    daemon_reload: yes
  tags: ['time_sync', 'handlers']

- name: restart chrony
  systemd:
    name: chrony
    state: restarted
    daemon_reload: yes
  tags: ['time_sync', 'handlers']

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
  tags: ['time_sync', 'handlers']

- name: restart cron
  systemd:
    name: cron
    state: restarted
  tags: ['time_sync', 'handlers']

- name: restart systemd-logind
  systemd:
    name: systemd-logind
    state: restarted
  tags: ['time_sync', 'handlers']

- name: reload systemd
  systemd:
    daemon_reload: yes
  tags: ['time_sync', 'handlers']