disable_existing_loggers: false
formatters:
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'
  standard:
    format: '%(asctime)s [%(name)s] %(levelname)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
  file:
    backupCount: 5
    class: logging.handlers.RotatingFileHandler
    filename: /home/kali/Desktop/AutoBot/logs/system.log
    formatter: json
    maxBytes: 10485760
root:
  handlers:
  - file
  - console
  level: INFO
version: 1
