---
# Redis role handlers

- name: restart redis-stack
  systemd:
    name: redis-stack-server
    state: restarted
  become: yes

- name: reload systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: reload firewall
  ufw:
    state: reloaded
  become: yes
